feat(web): display users companies
imPBH/StockManager pull request #7
Opened 2023-04-20 15:15 UTC by Kasoro47

2023-04-20 15:22 UTC, imPBH requested changes
Mock data instead of harcoding them.
Replace "Choose the companies that you want to display" by something like "Choose your company"

2023-04-20 16:00 UTC, imPBH commented
![](https://github.trello.services/images/mini-trello-icon.png) [8# Display users companies](https://trello.com/c/qVWoy3QM/16-display-users-companies)

2023-04-20 18:24 UTC, nos193 approved these changes

2023-04-20 18:25 UTC, nos193 approved these changes

2023-04-21 06:53 UTC, imPBH approved these changes

2023-04-21 06:53 UTC, merged